image: node:18-bullseye-slim

stages:
  - install
  - lint
  - deploy

.snippets:
  pnpm:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store

install:
  stage: install
  before_script:
    - !reference [.snippets, pnpm]
  script:
    - pnpm install
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_REF_PROTECTED == "true" && $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "web"
  tags:
    - personal

lint:
  stage: lint
  before_script:
    - !reference [.snippets, pnpm]
    - pnpm install
  script:
    - pnpm check:astro
    - pnpm check:svelte
    - pnpm lint
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
    policy: pull
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_REF_PROTECTED == "true" && $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "web"
  tags:
    - personal

deploy production:
  stage: deploy
  before_script:
    - !reference [.snippets, pnpm]
    - pnpm install
  variables:
    CLOUDFLARE_API_TOKEN: '$CLOUDFLARE_API_TOKEN'
    CLOUDFLARE_ACCOUNT_ID: '$CLOUDFLARE_ACCOUNT_ID'
    PUBLIC_WEBSOCKET_URI: '$PUBLIC_WEBSOCKET_URI'
  script:
    - npm i -g wrangler
    - pnpm build
    - wrangler pages deploy dist --project-name=$CI_PROJECT_NAME
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
    policy: pull
  rules:
    - if: $CI_COMMIT_REF_NAME == "main" && $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "web"
  tags:
    - personal

deploy preview:
  stage: deploy
  before_script:
    - !reference [.snippets, pnpm]
    - pnpm install
  variables:
    CLOUDFLARE_API_TOKEN: '$CLOUDFLARE_API_TOKEN'
    CLOUDFLARE_ACCOUNT_ID: '$CLOUDFLARE_ACCOUNT_ID'
    PUBLIC_WEBSOCKET_URI: '$PUBLIC_WEBSOCKET_URI'
  script:
    - npm i -g wrangler
    - pnpm build
    - wrangler pages deploy dist --project-name=$CI_PROJECT_NAME --branch=$CI_COMMIT_REF_NAME
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
    policy: pull
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_REF_NAME != "main"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  tags:
    - personal
